//
//  HomeWorker.swift
//  ScrollingList
//
//  Created by Vishnu Prasath on 17/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class HomeWorker {
    var searchTerm: String!
    private var searchAPI: SearchYelpAPI?
    
    init(searchTerm: String) {
        self.searchTerm = searchTerm
        searchAPI = SearchYelpAPI(searchTerm: searchTerm)
    }
    
    init() { }
    
    func searchWithYelpAPI(completion: ResultCompletion?) {
        let request = searchAPI ?? SearchYelpAPI(searchTerm: searchTerm)
        
        AF.request(request).responseDecodable(decoder: JSONDecoder(), completionHandler: { (response: DataResponse<YelpResponse, AFError>) in
            debugPrint("******* URL *******", response.request?.url?.absoluteString as Any)
            switch response.result {
            case .success(let value):
                completion?(value, nil)
            case .failure(let error):
                completion?(nil, error)
            }
        })
    }
    
}
